package com.hansck.shadowingu.database

/**
 * Created by Hans CK on 13-Jun-18.
 */
enum class QueryEnum {

	INSERT_UPDATE_USER, INSERT_AVATARS, INSERT_STAGES, INSERT_BADGES, INSERT_TITLES, INSERT_WORDS,
	UPDATE_USER, BUY_AVATAR, UPDATE_STAGE, UPDATE_BADGE, UPDATE_TITLE,
	GET_USERS, GET_AVATARS, GET_STAGES, GET_BADGES, GET_TITLES, GET_WORDS, GET_LEVELS
}